language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
script: .grailsw clean
	&& ./grailsw clean-all
	&& ./grailsw refresh-dependencies
  && ./grailsw "test-app unit:"
  && ./grailsw "war"
